name: Update Calendar

on:
  workflow_dispatch:   # só manual (para testar primeiro)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test step
        run: echo "Workflow está a funcionar!"
